name-template: "Example title - v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
exclude-labels:
  - "skip-changelog"
categories:
  - title: "New Features"
    when:
      labels:
        - "feature"
        - "enhancement"
  - title: "Bug Fixes"
    when:
      labels:
        - "fix"
        - "bugfix"
        - "bug"
  - title: "Dependencies"
    collapse-after: 2
    when:
      labels:
        - "dependencies"
        - "dependency"
  - title: "Maintenance"
    when:
      labels:
        - "chore"
        - "maintenance"
  - title: "Translations"
    when:
      labels:
        - "translation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/$OWNER/$REPOSITORY/v$RESOLVED_VERSION/total.svg)](https://github.com/$OWNER/$REPOSITORY/releases/v$RESOLVED_VERSION)

  <!--
  ### Checklist for release
  - Run pre-commit checks
  - Run make bump - select proper variant in Makefile
  - Review the draft below and update if needed
  -->

  ## Changes

  $CHANGES

autolabeler:
  - label: "maintenance"
    files:
      - "*.md"
      - ".github/*"
  - label: "bugfix"
    title:
      - "/fix/i"
  - label: "code quality"
    title:
      - "lint"
  - label: "translation"
    title:
      - "Lokalise:"
    files:
      - "**/translations/*.json"
  - label: "development tools"
    files:
      - ".devcontainer/*"
      - ".devcontainer.json"
      - "Makefile"
      - "setup.cfg"
      - "pyproject.toml"
      - ".ruff.toml"
      - ".pre-commit-config.yaml"
